name: repo_viewer
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  auto_route: ^3.2.2
  dartz: ^0.10.1
  dio: ^4.0.4
  flash: ^2.0.3+2
  flutter:
    sdk: flutter
  flutter_hooks: ^0.18.2
  flutter_secure_storage: ^5.0.2
  freezed_annotation: ^1.1.0
  hooks_riverpod: ^1.0.3
  http: ^0.13.4
  oauth2: ^2.0.0
  webview_flutter: ^3.0.0

dev_dependencies:
  auto_route_generator: ^3.2.1
  build_runner: ^2.1.7
  flutter_test:
    sdk: flutter
  freezed: ^1.1.1
  lint: ^1.8.2

flutter:
  uses-material-design: true
